project:
  type: website
  output-dir: "docs"

website:
  title: "Mawuse Tawiah"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Portfolio"
        file: portfolio.qmd
      - text: "CV"
        file: cv.qmd
    right:
      - icon: github
        href: https://github.com/tmawuse
      - icon: linkedin
        href: https://linkedin.com/in/tmawuse
format:
  html:
    theme:
      - morph
      - brand
    css: styles.css

editor: visual

